### ISSUE TITLE
[Forked due unattended]

### ISSUE THREAD

**Issue by busslina** [busslina/dart-duration#1]
https://github.com/desktop-dart/duration/issues/69

Include snippet:
```yaml
dependencies:
  duration:
      git:
        url: https://github.com/busslina/dart-duration.git
        ref: master
```
